class TextTransformer:
    def condition_text(self, original_text: str, intent: dict) -> str:
        """
        Transforms structured intent into TTS-friendly expressive input.
        Now uses the refined text generated by the LLM.
        """
        emotion = intent.get("emotion", "calm")
        style = intent.get("style", "narration")
        refined_text = intent.get("refined_text", original_text)
        
        return f"[{emotion} tone, {style}] {refined_text}"
